name: CI-runner-midway2

on:
  push:
    branches:
      - github_ci
      - main
      - trunk-merge/**
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
  workflow_call:

jobs:
  test:
    runs-on: [self-hosted, linux]
    strategy:
      fail-fast: false
      matrix:
        os: [linux]
        python-version: [3.6]
    steps:
      - uses: actions/checkout@v3

      - name: Install python dependecies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install dill jaxlib "jax-md>=0.2.7" jaxopt pytest matplotlib

      - name: Install pysages
        run: pip3 install .

      - name: Run tests
        run: |
          pytest
          mkdir /tmp/test_plots
          mv *.pdf /tmp/test_plots

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test_plots
          path: /tmp/test_plots

  doc-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install python dependecies
        run: |
          python -m pip install --upgrade pip
          pip install dill jaxlib "jax-md>=0.2.7" jaxopt pytest pylint flake8
          pip install -r docs/requirements.txt
      - name: Install pysages
        run: pip install .
      - name: Build documentation
        run: cd docs && sphinx-build -b spelling -W --keep-going source build
