name: Docker CI Midway2

on:
  push:
    branches:
      - github_ci
      - main
      - trunk-merge/**
    paths-ignore:
      - "README.md"
      - "docs/*"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "docs/*"

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: pysages:latest
          outputs: type=docker,dest=/tmp/pysages.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pysages
          path: /tmp/pysages.tar
          retention-days: 1

  abf-alanine-dipeptide-openmm:
    runs-on: [self-hosted]
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: pysages
          path: /tmp
      - name: Load and run test
        run: |
          docker load --input /tmp/pysages.tar
          docker run -t pysages bash -c "cd PySAGES/examples/openmm/abf/ && python3 ./alanine-dipeptide_openmm.py"
  
  harmonic-bias-hoomd:
    runs-on: [self-hosted]
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: pysages
          path: /tmp
      - name: Load and run test
        run: |
          docker load --input /tmp/pysages.tar
          docker run -v/tmp:/tmp -t pysages bash -c "cd PySAGES/examples/hoomd-blue/harmonic_bias/ && ./run.sh && mv hist.pdf /tmp/"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: harmonic-hist.pdf
          path: /tmp/hist.pdf
          retention-days: 7

