name: CI-runner

on:
  push:
    branches:
      - github-runner
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  test:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: [3.7, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jaxlib pytest matplotlib

      - name: Install pysages
        run: pip install .

      - name: Run tests
        run: |
          echo "Will run: srun --account=rcc-staff --reservation=gpu_test --partition=gpu -n1 pytest"



